EX_NAME=adi2_l2tile
EX_FILE=adi2_l2tile.c
FN_LIST="func"
BB_LIST="ignore"
PRF_DATA_FILE="gep_adi2_l2tile_eqclass.csv"
PRF_FL="linv_adi2_l2tile.txt"
BCNAME="adi2_l2tile"
LEVEL=../..

include ../../common.mk
