EX_NAME=gemver2_l2tile
EX_FILE=gemver2_l2tile.c
FN_LIST="func"
BB_LIST="ignore"
PRF_DATA_FILE="gep_gemver2_l2tile_eqclass.csv"
PRF_FL="linv_gemver2_l2tile.txt"
BCNAME="gemver2_l2tile"
LEVEL=../..

include ../../common.mk
