EX_NAME=fdtd-1d2_tile
EX_FILE=fdtd-1d2_tile.c
FN_LIST="func"
BB_LIST="ignore"
PRF_DATA_FILE="gep_fdtd-1d2_tile_eqclass.csv"
PRF_FL="linv_fdtd-1d2_tile.txt"
BCNAME="fdtd-1d2_tile"
LEVEL=../..

include ../../common.mk
