EX_NAME=gemver2_ncbt
EX_FILE=gemver2_ncbt.c
FN_LIST="func"
BB_LIST="ignore"
PRF_DATA_FILE="gep_gemver2_ncbt_eqclass.csv"
PRF_FL="linv_gemver2_ncbt.txt"
BCNAME="gemver2_ncbt"
LEVEL=../..

include ../../common.mk
