EX_NAME=fdtd-1d2_ncbt
EX_FILE=fdtd-1d2_ncbt.c
FN_LIST="func"
BB_LIST="ignore"
PRF_DATA_FILE="gep_fdtd-1d2_ncbt_eqclass.csv"
PRF_FL="linv_fdtd-1d2_ncbt.txt"
BCNAME="fdtd-1d2_ncbt"
LEVEL=../..

include ../../common.mk
