EX_NAME=lu2_unroll
EX_FILE=lu2_unroll.c
FN_LIST="func"
BB_LIST="ignore"
PRF_DATA_FILE="gep_lu2_unroll_eqclass.csv"
PRF_FL="linv_lu2_unroll.txt"
BCNAME="lu2_unroll"
LEVEL=../..

include ../../common.mk
