EX_NAME=fdtd-1d2_orig
EX_FILE=fdtd-1d2_orig.c
FN_LIST="func"
BB_LIST="ignore"
PRF_DATA_FILE="gep_fdtd-1d2_orig_eqclass.csv"
PRF_FL="linv_fdtd-1d2_orig.txt"
BCNAME="fdtd-1d2_orig"
LEVEL=../..

include ../../common.mk
