EX_NAME=dct2_l2tile
EX_FILE=dct2_l2tile.c
FN_LIST="func"
BB_LIST="ignore"
PRF_DATA_FILE="gep_dct2_l2tile_eqclass.csv"
PRF_FL="linv_dct2_l2tile.txt"
BCNAME="dct2_l2tile"
LEVEL=../..

include ../../common.mk
