EX_NAME=gemver2_tile
EX_FILE=gemver2_tile.c
FN_LIST="func"
BB_LIST="ignore"
PRF_DATA_FILE="gep_gemver2_tile_eqclass.csv"
PRF_FL="linv_gemver2_tile.txt"
BCNAME="gemver2_tile"
LEVEL=../..

include ../../common.mk
