EX_NAME=jac2_unroll
EX_FILE=jac2_unroll.c
FN_LIST="func"
BB_LIST="ignore"
PRF_DATA_FILE="gep_jac2_unroll_eqclass.csv"
PRF_FL="linv_jac2_unroll.txt"
BCNAME="jac2_unroll"
LEVEL=../..

include ../../common.mk
