EX_NAME=lu2_l2tile
EX_FILE=lu2_l2tile.c
FN_LIST="func"
BB_LIST="ignore"
PRF_DATA_FILE="gep_lu2_l2tile_eqclass.csv"
PRF_FL="linv_lu2_l2tile.txt"
BCNAME="lu2_l2tile"
LEVEL=../..

include ../../common.mk
