EX_NAME=seidel2_tile
EX_FILE=seidel2_tile.c
FN_LIST="func"
BB_LIST="ignore"
PRF_DATA_FILE="gep_seidel2_tile_eqclass.csv"
PRF_FL="linv_seidel2_tile.txt"
BCNAME="seidel2_tile"
LEVEL=../..

include ../../common.mk
