EX_NAME=seidel2_orig
EX_FILE=seidel2_orig.c
FN_LIST="func"
BB_LIST="ignore"
PRF_DATA_FILE="gep_seidel2_orig_eqclass.csv"
PRF_FL="linv_seidel2_orig.txt"
BCNAME="seidel2_orig"
LEVEL=../..

include ../../common.mk
