EX_NAME=gemver2_orig
EX_FILE=gemver2_orig.c
FN_LIST="func"
BB_LIST="ignore"
PRF_DATA_FILE="gep_gemver2_orig_eqclass.csv"
PRF_FL="linv_gemver2_orig.txt"
BCNAME="gemver2_orig"
LEVEL=../..

include ../../common.mk
