EX_NAME=jac2d2_orig
EX_FILE=jac2d2_orig.c
FN_LIST="func"
BB_LIST="ignore"
PRF_DATA_FILE="gep_jac2d2_orig_eqclass.csv"
PRF_FL="linv_jac2d2_orig.txt"
BCNAME="jac2d2_orig"
LEVEL=../..

include ../../common.mk
