EX_NAME=jac2d2_ncbt
EX_FILE=jac2d2_ncbt.c
FN_LIST="func"
BB_LIST="ignore"
PRF_DATA_FILE="gep_jac2d2_ncbt_eqclass.csv"
PRF_FL="linv_jac2d2_ncbt.txt"
BCNAME="jac2d2_ncbt"
LEVEL=../..

include ../../common.mk
