EX_NAME=seidel2_ncbt
EX_FILE=seidel2_ncbt.c
FN_LIST="func"
BB_LIST="ignore"
PRF_DATA_FILE="gep_seidel2_ncbt_eqclass.csv"
PRF_FL="linv_seidel2_ncbt.txt"
BCNAME="seidel2_ncbt"
LEVEL=../..

include ../../common.mk
