EX_NAME=seidel2_l2tile
EX_FILE=seidel2_l2tile.c
FN_LIST="func"
BB_LIST="ignore"
PRF_DATA_FILE="gep_seidel2_l2tile_eqclass.csv"
PRF_FL="linv_seidel2_l2tile.txt"
BCNAME="seidel2_l2tile"
LEVEL=../..

include ../../common.mk
