EX_NAME=mvt2_l2tile
EX_FILE=mvt2_l2tile.c
FN_LIST="func"
BB_LIST="ignore"
PRF_DATA_FILE="gep_mvt2_l2tile_eqclass.csv"
PRF_FL="linv_mvt2_l2tile.txt"
BCNAME="mvt2_l2tile"
LEVEL=../..

include ../../common.mk
